from .logos import create_logo_grid, LOGO_FILENAMES
from .matrix_utils import (
    CHAPTER0_MATRIX_DATA,
    CHAPTER3_MATRIX_DATA,
    CHAPTER5_EDGES,
    CHAPTER8_MATRIX_DATA,
    CHAPTER8_A2_DATA,
    CHAPTER8_TRIANGLE_DATA,
    CHAPTER8_TRIANGLES,
    CHAPTER8_PER_NODE_TRIANGLES,
    create_labeled_matrix,
    create_sparse_matrix,
    create_incidence_matrices,
    hide_zero_entries,
    get_non_zero_positions,
    get_zero_positions,
)
from .graph_utils import (
    create_adjacency_digraph,
    create_undirected_graph,
    create_small_graph_from_matrix,
    set_vertex_fill_preserve_label,
    animate_vertex_fill,
    create_multigraph_visual,
    create_hyperedge_region,
    create_bipartite_graph,
    get_edge_between_vertices,
    highlight_triangle,
    color_nodes_by_value,
    create_karate_graph,
    KARATE_EDGES,
    KARATE_TRIANGLE_COUNTS,
    KARATE_TOTAL_TRIANGLES,
)
from .speech import get_speech_service, setup_scene, is_prod_mode
